// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoWf7DgIDbpNyBxWZpkU8Vgt696Pr_b_Q',
    appId: '1:928907631888:web:662f34795a6a9181805995',
    messagingSenderId: '928907631888',
    projectId: 'activity-5c3f1',
    authDomain: 'activity-5c3f1.firebaseapp.com',
    storageBucket: 'activity-5c3f1.firebasestorage.app',
    measurementId: 'G-R52W15YV3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74-7W2GuziosfcKvi9zUUNoz_Ybwpu6A',
    appId: '1:928907631888:android:220239e2d35b529f805995',
    messagingSenderId: '928907631888',
    projectId: 'activity-5c3f1',
    storageBucket: 'activity-5c3f1.firebasestorage.app',
  );
}
